GrNM: DFG_GRN/DFG_Dynamics_AR1_MStep.m File Reference
DFG_Dynamics_AR1_MStep.m File Reference
Functions
function [ n_m_steps , eta_coeff ] = DFG_Dynamics_AR1_MStep (z, eta, params, model_num, deltaT)
function [ eta , e ] = DFGDynamicsAR1MStep>Dynamics_AR1_LineSearch (zIn, zTarget, alpha0, alpha1, coeff_delta, etas, params, energies, deltaWDyna, deltaBDyna, depth, model_num)
function [ deltaWDyna , deltaBDyna ] = DFGDynamicsAR1MStep>Dynamics_AR1_AddRegularizer (deltaWDyna, deltaBDyna, lambda, model_num)
function DFGDynamicsAR1MStep>Dynamics_AR1_ApplyGradient (eta, deltaWDyna, deltaBDyna, model_num)
function [ weightsCopy , biasCopy ] = DFGDynamicsAR1MStep>ModelCopy (model_num)
function DFGDynamicsAR1MStep>ModelPaste (weightsCopy, biasCopy, model_num)
Function Documentation
function [n_m_steps , eta_coeff ] = DFG_Dynamics_AR1_MStep (z, eta, params, model_num, deltaT)
Definition at line 17 of file DFG_Dynamics_AR1_MStep.m.
References DFG_Dynamics_AR1_BackProp(), DFG_Dynamics_AR1_ComputeKineticCoeff(), DFG_Dynamics_AR1_Forward(), DFG_Dynamics_AR1_GetInputOutput(), and DFG_Energy_Gaussian().
Referenced by DFG_Learn().
function [deltaWDyna , deltaBDyna ] = DFGDynamicsAR1MStep>Dynamics_AR1_AddRegularizer (deltaWDyna, deltaBDyna, lambda, model_num)
Definition at line 225 of file DFG_Dynamics_AR1_MStep.m.
function DFGDynamicsAR1MStep>Dynamics_AR1_ApplyGradient (eta, deltaWDyna, deltaBDyna, model_num)
Definition at line 236 of file DFG_Dynamics_AR1_MStep.m.
function [eta , e ] = DFGDynamicsAR1MStep>Dynamics_AR1_LineSearch (zIn, zTarget, alpha0, alpha1, coeff_delta, etas, params, energies, deltaWDyna, deltaBDyna, depth, model_num)
Definition at line 169 of file DFG_Dynamics_AR1_MStep.m.
References DFG_Dynamics_AR1_Forward(), DFG_Energy_Gaussian(), and DFG_QuadraticLineSearch().
function [weightsCopy , biasCopy ] = DFGDynamicsAR1MStep>ModelCopy (model_num)
Definition at line 254 of file DFG_Dynamics_AR1_MStep.m.
function DFGDynamicsAR1MStep>ModelPaste (weightsCopy, biasCopy, model_num)
Definition at line 264 of file DFG_Dynamics_AR1_MStep.m.