GrNM: DFG_GRN/DFG_Dynamics_AR1_Lasso.m File Reference
DFG_Dynamics_AR1_Lasso.m File Reference
Functions
function DFG_Dynamics_AR1_Lasso (z, params, model_num, deltaT)
Function Documentation
function DFG_Dynamics_AR1_Lasso (z, params, model_num, deltaT)
Definition at line 17 of file DFG_Dynamics_AR1_Lasso.m.
References bolasso(), DFG_Dynamics_AR1_ComputeKineticCoeff(), DFG_Dynamics_AR1_Forward(), DFG_Dynamics_AR1_GetInputOutput(), and DFG_Energy_Gaussian().
Referenced by DFG_Learn().