GrNM: DFG_GRN/DFG_Infer.m File Reference
DFG_Infer.m File Reference
Functions
function [ zBar , yBar , meter , zBarOut ] = DFG_Infer (z, y, yKnown, params, eta_z, meter, traceStr, model_num, dT)
function [ z_smoothness , z_sparsity ] = DFGInfer>StatisticsLatentVar (z)
Function Documentation
function [zBar , yBar , meter , zBarOut ] = DFG_Infer (z, y, yKnown, params, eta_z, meter, traceStr, model_num, dT)
Definition at line 17 of file DFG_Infer.m.
References DFG_Dynamics_AR1_BackProp(), DFG_Dynamics_AR1_ComputeKineticCoeff(), DFG_Dynamics_AR1_Forward(), DFG_Energy_Gaussian(), and DFG_MeterUpdate().
Referenced by DFG_Learn(), and GRNEvaluateModelsAR1>Evaluate().
function [z_smoothness , z_sparsity ] = DFGInfer>StatisticsLatentVar (z)
Definition at line 248 of file DFG_Infer.m.
References DFG_ComputeSparsity().