GrNM: DFG_GRN/DFG_Learn.m File Reference
DFG_Learn.m File Reference
Functions
function [ yStarTrain , zStarTrain ] = DFG_Learn (yTrain, yKnownTrain, yTest, yKnownTest, params, model_num, deltaTtrain, deltaTtest)
function DFGLearn>ModelInit (dim_z, dynamic_model, observation_model, params, n, y)
function DFGLearn>ModelCorrelationPrior (yTrain, dim_z, params, model_num)
function order = DFGLearn>ScrambleSeq (n_seq)
function DFGLearn>MeterUpdateParams (n_m_steps, model_num, eta_coeff)
Function Documentation
function [yStarTrain , zStarTrain ] = DFG_Learn (yTrain, yKnownTrain, yTest, yKnownTest, params, model_num, deltaTtrain, deltaTtest)
Definition at line 17 of file DFG_Learn.m.
References DFG_CharacterizeParams(), DFG_Data_MeanSignal(), DFG_Dynamics_AR1_DistribDelta(), DFG_Dynamics_AR1_Lasso(), DFG_Dynamics_AR1_MStep(), DFG_Infer(), DFG_MeterUpdate(), DFG_MeterUpdate_Comparison2TargetGRN(), DFG_MeterUpdate_TrendError(), DFG_Model_Archive(), DFG_Model_RetrieveBest(), DFG_Model_SaveBest(), and DFG_Trace_AR1_Id().
Referenced by GRN_Batch_AR1(), and GRN_Batch_Arabidopsis().
function DFGLearn>MeterUpdateParams (n_m_steps, model_num, eta_coeff)
Definition at line 416 of file DFG_Learn.m.
References DFG_CharacterizeParams(), and DFG_MeterUpdate().
function DFGLearn>ModelCorrelationPrior (yTrain, dim_z, params, model_num)
Definition at line 390 of file DFG_Learn.m.
function DFGLearn>ModelInit (dim_z, dynamic_model, observation_model, params, n, y)
Definition at line 356 of file DFG_Learn.m.
function order = DFGLearn>ScrambleSeq (n_seq)
Definition at line 409 of file DFG_Learn.m.