GrNM: DFG_GRN/GRN_Batch_MultiModel_AR1.m File Reference
GRN_Batch_MultiModel_AR1.m File Reference
Functions
function GRN_Batch_MultiModel_AR1 (n_models, script_name, varargin)
Function Documentation
function GRN_Batch_MultiModel_AR1 (n_models, script_name, varargin)
Definition at line 17 of file GRN_Batch_MultiModel_AR1.m.
References GRN_Batch_AR1(), and GRN_EvaluateModels_AR1().
Referenced by GrNM_model().