GrNM: DFG_GRN/GRN_Batch_AR1.m File Reference
GRN_Batch_AR1.m File Reference
Functions
function params = GRN_Batch_AR1 (model_num, script_name, varargin)
Function Documentation
function params = GRN_Batch_AR1 (model_num, script_name, varargin)
Definition at line 17 of file GRN_Batch_AR1.m.
References DFG_InitOctave(), DFG_Learn(), DFG_Params_Modify(), and GRN_Normalize().
Referenced by GRN_Batch_MultiModel_AR1().