GrNM: Arabidopsis/Script_Arabidopsis76_Leave1.m File Reference
Script_Arabidopsis76_Leave1.m File Reference
Leave-out-last analysis, 76 genes, RMA data gradient state-space optimization of kinetic equation, linear dynamics no data normalization.
Functions
function Script_Arabidopsis76_Leave1 ()
Leave-out-last analysis, 76 genes, RMA data gradient state-space optimization of kinetic equation, linear dynamics no data normalization.
Detailed Description
Leave-out-last analysis, 76 genes, RMA data gradient state-space optimization of kinetic equation, linear dynamics no data normalization.
Definition in file Script_Arabidopsis76_Leave1.m.
Function Documentation
function Script_Arabidopsis76_Leave1 ()
Leave-out-last analysis, 76 genes, RMA data gradient state-space optimization of kinetic equation, linear dynamics no data normalization.
Definition at line 17 of file Script_Arabidopsis76_Leave1.m.
References DFG_Params_Default_Arabidopsis(), GRN_readDatafile(), Script_Arabidopsis_ConsistentGenes(), and Script_Arabidopsis_DataLeave1().
Referenced by Script_Arabidopsis76_Leave1_Brown(), Script_Arabidopsis76_Leave1_Brown_LARS(), Script_Arabidopsis76_Leave1_LARS(), Script_Arabidopsis76_Leave1_Norm(), and Script_Arabidopsis76_Leave1_Norm_Brown().