GrNM: libs/bolasso/lars_test.m File Reference
lars_test.m File Reference
Example script for performing LASSO regression on the diabetes data set.
Functions
function lars_test ()
Example script for performing LASSO regression on the diabetes data set.
Detailed Description
Example script for performing LASSO regression on the diabetes data set.
Definition in file lars_test.m.
Function Documentation
function lars_test ()
Example script for performing LASSO regression on the diabetes data set.
Definition at line 17 of file lars_test.m.
References center(), cvplot(), lars(), and normalize().