GrNM: libs/bolasso/normalize.m File Reference
normalize.m File Reference
NORMALIZE Normalize the observations of a data matrix. X = NORMALIZE(X) centers and scales the observations of a data matrix such that each variable (column) has unit length.
Functions
function X = normalize (X)
NORMALIZE Normalize the observations of a data matrix. X = NORMALIZE(X) centers and scales the observations of a data matrix such that each variable (column) has unit length.
Detailed Description
NORMALIZE Normalize the observations of a data matrix. X = NORMALIZE(X) centers and scales the observations of a data matrix such that each variable (column) has unit length.
Definition in file normalize.m.
Function Documentation
function X = normalize (X)
NORMALIZE Normalize the observations of a data matrix. X = NORMALIZE(X) centers and scales the observations of a data matrix such that each variable (column) has unit length.
Author: Karl Skoglund, IMM, DTU, kas@i.nosp@m.mm.d.nosp@m.tu.dk
Definition at line 17 of file normalize.m.
References center().
Referenced by bolasso(), lars_test(), larsen_test(), and spca_test().