GrNM: libs/bolasso/synthesizeData.m File Reference
synthesizeData.m File Reference
Generate synthetic data as per section 4.1 in Bolasso: Model Consistent Lasso Estimation throught the Bootstrap by Fracis R. Bach, available at www.di.ens.fr/~fbach/icml_bolasso.pdf.
Functions
function [ Xdata , ydata , W , check ] = synthesizeData (n, d, r, nDataSets, consistent)
Generate synthetic data as per section 4.1 in Bolasso: Model Consistent Lasso Estimation throught the Bootstrap by Fracis R. Bach, available at www.di.ens.fr/~fbach/icml_bolasso.pdf.
Detailed Description
Generate synthetic data as per section 4.1 in Bolasso: Model Consistent Lasso Estimation throught the Bootstrap by Fracis R. Bach, available at www.di.ens.fr/~fbach/icml_bolasso.pdf.
Definition in file synthesizeData.m.
Function Documentation
function [ Xdata , ydata , W , check ] = synthesizeData (n, d, r, nDataSets, consistent)
Generate synthetic data as per section 4.1 in Bolasso: Model Consistent Lasso Estimation throught the Bootstrap by Fracis R. Bach, available at www.di.ens.fr/~fbach/icml_bolasso.pdf.
n - number of examples d - number of features r - number of relevant features
nDataSets - number of data sets, each with the above specs all drawn from the same distribution, i.e. all of the X's drawn using the same cov matrix and y's generated using the same loading vector, W.
consistent - if true only sign consistent data is returned. If false, only sign inconsistent data is returned. Sign consistency is w.r.t. equation 2 in Bolasso: Model Consistent Lasso Estimation throught the Bootstrap by Francis R. Bach. Available at www.di.ens.fr/~fbach/icml_bolasso.pdf ||(Q_{J^cJ})*(Q_{JJ}^-1)*sign(W_J)||_inf <= 1
Xdata - A cell array of n-by-d random matrices whose only relevent features are columns 1:r.
ydata - A cell array of n-by-1 target/output random vectors.
W - the d-by-1 random loading vector used to generate all of the y vectors.
check - the numerical value of the consistency check, i.e. ||(Q_{J^cJ})*(Q_{JJ}^-1)*sign(W_J)||_inf
If nDataSets = 1, X,y are unwrapped yielding numeric matricies not cell arrays.
Code by Matthew Dunham
Definition at line 17 of file synthesizeData.m.
References corrcov(), mvnrnd(), and normrnd().
Referenced by bolassoSimpleDemo().